#!/usr/bin/env bash

SCRIPT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
ROOT_DIR=${SCRIPT_DIR%/scripts*}

# set language from positional parameters of mindex script
LANG=$1
source ${SCRIPT_DIR}/mlang "$LANG" || exit 1

# clean main page for new notes to be inserted
# inherited index_location variable from mlang script above
echo > "$INDEX_LOCATION"

while IFS= read -r note; do

  # get note's first line which contains date
  date=$( sed -n '1p' < "$note" )

  # get note's third line which contains name
  name=$( sed -n '3p' < "$note" )

  dir_md=${note%/README.md}
  OUTPUT_DIR=${dir_md/notes/}

  # set the output html file for each note
  link=${OUTPUT_DIR#*docs/}
  link="$link/${date}.html"

  echo $link

  # creating clickable links on main page (index.md)
  notelink="[${date}: ${name#\# }](${link})"
  printf '%s\n\n' "$notelink" >> "$INDEX_LOCATION"

# got the search_folder variable from mlang script above
done < <( find "$SEARCH_FOLDER" -mindepth 2 \
            -iname '*.md' | sort -Vr )
