#!/usr/bin/env bash

# created: 20231014144115
# author: m7tkr
# usage: `source ./norder` from root/
# purpose: when rm some notes, list of dirs in notes/ becomes
#          disorder. script names folders by numeric order

declare -i number
number=1

while read -r note; do
    
    # change dir of folder
    echo "echoed \"mv ${note}/ ${note%%/*}/${number}/\""

    number=$(( number+1 ))
done < <( find notes/ -mindepth 1 -type d | sort -V )
    # -mindepth 1: exclude search dir
    # -V --version sort here
