https://www.rustamjafar.com/ar

https://www.rustamjafar.com/en

https://www.rustamjafar.com/ru

'''

:toc:

== ع

كيف أختار لغة عندما أكتب ملحوظة؟

أساسيا، أستخدم لغة الأصل. هكذا، إذ وُجد شيء ما بالعربي فلغة الملحوظة عربي. الشيء
النفسه للغات الأخرى. أما أفكاري الشخصية فأستخدم العربي لأنه لغتي الفضلية من ثلاث
أعلاه.

== en

how do i chose the language when writing notes?

basically, i use the language of the original. so, when something is found in
english, the note is written in englsh. the same with other two languages. but
when i want to express my own thoughts, most of the time i will use arabic,
for out of three languages above this is the language i like the most.

== ру

как я выбираю язык для записи заметок?

в основе, я использую язык оригинала. таким образом, если инфо найдено на
русском языке, то сама заметка на русском. тоже самое и для других двух языков.
что касается моих собственных заключений, то они будут изложены на арабском,
потому что из трех языков выше, этот язык, который мне нравится наиболее.
